from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.schemas.ai_assistant import ChatRequest, ChatResponse
from app.models.doctor import Doctor
from app.models.department import Department

router = APIRouter()

# ---------------------------------------------------------------------
# Expanded Health FAQs (full‑question matching)
# ---------------------------------------------------------------------
FAQS = {
    # ----- General Hospital -----
    "what are your working hours": "Our hospital operates 24/7. Outpatient departments are open from 9 AM to 6 PM, Monday to Saturday.",
    "do you have emergency services": "Yes, we have a 24/7 emergency department. Call our emergency hotline: 18001234567.",
    "where is the hospital located": "MediCare Plus is located at 123 Health Avenue, Medical City.",
    "how do i contact support": "You can reach our support team at support@medicareplus.com or call 18001234567.",

    # ----- Appointments -----
    "how do i book an appointment": "You can book an appointment by visiting 'Book Appointment' in your patient dashboard. Choose a doctor, pick a date/time, and submit.",
    "can i cancel an appointment": "Yes, you can cancel or reschedule an appointment from 'My Appointments' in your dashboard.",
    "how do i view my appointments": "Go to 'My Appointments' in the sidebar. You’ll see all upcoming and past appointments.",

    # ----- Prescriptions & Medications -----
    "how do i get a prescription refill": "Please consult your doctor for a refill. You can request a consultation from your dashboard.",
    "how do i view my prescriptions": "Navigate to 'Prescriptions' in your dashboard. You can also download a PDF of any prescription.",

    # ----- Lab Tests -----
    "what tests do you offer": "We offer a wide range of laboratory tests including blood tests, urine tests, X-rays, and more. You can request a test from 'Lab Tests' in your dashboard.",
    "how do i get my lab results": "Lab results are uploaded by your doctor. You can view them under 'Lab Tests' once they are ready.",

    # ----- Insurance & Billing -----
    "what insurance plans do you accept": "We accept most major insurance plans including HealthGuard, LifeCare, and National Health.",
    "how do i file an insurance claim": "Go to 'Insurance' in your dashboard, select a verified policy, and click 'File a Claim'.",
    "what is the billing process": "After a service, a bill is generated by the admin or doctor. You can view and pay your bills under 'Billing'.",

    # ----- Health & Lifestyle -----
    "how can i lower my blood pressure": "Reduce salt intake, exercise regularly, manage stress, and take prescribed medications. Consult a cardiologist if needed.",
    "what should i do for a fever": "Rest, drink plenty of fluids, and take fever reducers like paracetamol. If fever persists beyond 3 days, see a doctor.",
    "how do i manage diabetes": "Monitor blood sugar regularly, follow a balanced diet, exercise, and take medications as prescribed. An endocrinologist can help.",
    "what are the symptoms of covid-19": "Common symptoms include fever, cough, shortness of breath, fatigue, and loss of taste or smell. Get tested if you have these symptoms.",
    "how to treat a common cold": "Rest, drink warm fluids, and use over-the-counter cold remedies. Antibiotics are not effective against viruses.",

    # ----- Doctors & Specialties -----
    "what does a cardiologist do": "A cardiologist specializes in heart and blood vessel diseases. They treat conditions like hypertension, heart attacks, and arrhythmias.",
    "what does a neurologist treat": "Neurologists treat disorders of the brain, spinal cord, and nerves, such as migraines, epilepsy, and Parkinson's disease.",
    "what does an orthopedist do": "Orthopedic doctors treat bone, joint, and muscle problems, including fractures, arthritis, and sports injuries.",
    "what does a pediatrician do": "Pediatricians provide medical care for infants, children, and adolescents, including vaccinations and developmental checkups.",
}

# ---------------------------------------------------------------------
# Keyword‑to‑FAQ mapping (for generic queries like "Health FAQs")
# ---------------------------------------------------------------------
KEYWORD_FAQ = {
    "health faqs": "I can answer many health‑related questions. Try asking:\n- 'What should I do for a fever?'\n- 'How can I lower my blood pressure?'\n- 'What are the symptoms of COVID-19?'",
    "medication information": "I can give you basic information about common medications. Try asking:\n- 'What is Paracetamol?'\n- 'What is Ibuprofen?'\n- 'Tell me about Metformin.'",
    "medical records": "You can view your medical records by navigating to 'Medical Records' in your patient sidebar. Doctors and admins can also access them.",
    "emergency": "If this is a life‑threatening emergency, please call our emergency hotline 18001234567 or go directly to the Emergency Department.",
}

# ---------------------------------------------------------------------
# Symptom‑to‑specialisation mapping
# ---------------------------------------------------------------------
SYMPTOM_MAP = {
    "heart": "Cardiologist",
    "chest pain": "Cardiologist",
    "breathing": "Pulmonologist",
    "asthma": "Pulmonologist",
    "skin": "Dermatologist",
    "rash": "Dermatologist",
    "bone": "Orthopedic",
    "fracture": "Orthopedic",
    "joint pain": "Orthopedic",
    "headache": "Neurologist",
    "migraine": "Neurologist",
    "stomach": "Gastroenterologist",
    "abdomen": "Gastroenterologist",
    "child": "Pediatrician",
    "pediatric": "Pediatrician",
    "eye": "Ophthalmologist",
    "vision": "Ophthalmologist",
    "ear": "ENT Specialist",
    "nose": "ENT Specialist",
    "throat": "ENT Specialist",
    "mental": "Psychiatrist",
    "depression": "Psychiatrist",
    "anxiety": "Psychiatrist",
    "women": "Gynecologist",
    "pregnancy": "Gynecologist",
    "dental": "Dentist",
    "tooth": "Dentist",
    "cancer": "Oncologist",
    "kidney": "Nephrologist",
    "urinary": "Urologist",
    "diabetes": "Endocrinologist",
    "thyroid": "Endocrinologist",
    "allergy": "Allergist",
    "cough": "Pulmonologist",
    "fever": "General Physician",
    "fatigue": "General Physician",
    "back pain": "Orthopedic",
    "neck pain": "Orthopedic",
    "sleep": "Neurologist",
    "weight loss": "Endocrinologist",
    "weight gain": "Endocrinologist",
    "hair loss": "Dermatologist",
}

# ---------------------------------------------------------------------
# Medication information lookup
# ---------------------------------------------------------------------
MEDICATION_INFO = {
    "paracetamol": "Paracetamol (Acetaminophen) is a pain reliever and fever reducer. Common dosage: 500mg every 4-6 hours, max 4g/day. Consult your doctor.",
    "ibuprofen": "Ibuprofen is an NSAID used for pain, fever, and inflammation. Typical dosage: 200-400mg every 4-6 hours. Take with food.",
    "amoxicillin": "Amoxicillin is an antibiotic used to treat bacterial infections. Dosage depends on infection type. Complete the full course as prescribed.",
    "metformin": "Metformin is an oral diabetes medicine that helps control blood sugar levels. Common dosage: 500mg twice daily or 850mg once daily with meals.",
    "aspirin": "Aspirin is used to reduce pain, fever, and inflammation. Low doses are also used to prevent blood clots. Consult a doctor before long-term use.",
    "omeprazole": "Omeprazole reduces stomach acid and is used for heartburn and acid reflux. Typical dosage: 20mg once daily before a meal.",
    "cetirizine": "Cetirizine is an antihistamine used for allergy symptoms. Common dosage: 10mg once daily.",
    "azithromycin": "Azithromycin is an antibiotic used for respiratory and other infections. Dosage varies. Always follow prescription.",
}

# ---------------------------------------------------------------------
def get_doctor_recommendations(symptom: str, db: Session):
    matched_specializations = set()
    for keyword, spec in SYMPTOM_MAP.items():
        if keyword in symptom.lower():
            matched_specializations.add(spec)

    if not matched_specializations:
        return None, "I couldn't determine a specific specialty from your symptoms. Please consult a general physician or use 'Find Doctors' to browse available doctors."

    doctors = db.query(Doctor).filter(Doctor.specialization.in_(matched_specializations)).all()
    if not doctors:
        return None, (f"No doctors with specialization(s) {', '.join(matched_specializations)} found in the system. "
                       "You can browse all doctors from the 'Find Doctors' page or ask the front desk for assistance.")

    reply = "Based on your symptoms, you may want to consult one of the following doctors:\n"
    for i, doc in enumerate(doctors[:3], 1):
        reply += f"{i}. Dr. (ID: {doc.id}) – {doc.specialization}, Exp: {doc.experience} yrs, Fee: ${doc.consultation_fee}\n"
    reply += "\nWould you like me to help you book an appointment with any of them?"
    return doctors[:3], reply

# ---------------------------------------------------------------------
@router.post("/chat", response_model=ChatResponse)
def chat(
    request: ChatRequest,
    db: Session = Depends(get_db)
):
    msg = request.message.strip().lower()

    # 1. Keyword‑FAQ matching (generic queries like "Health FAQs", "medical records")
    for keyword, answer in KEYWORD_FAQ.items():
        if keyword in msg:
            return ChatResponse(reply=answer)

    # 2. Exact FAQ matching (full question)
    for question, answer in FAQS.items():
        if question in msg:
            return ChatResponse(reply=answer)

    # 3. Medication lookup
    for drug, info in MEDICATION_INFO.items():
        if drug in msg:
            return ChatResponse(reply=info)

    # 4. Symptom‑based guidance & doctor recommendation
    symptom_keywords = ["symptom", "pain", "ache", "feeling", "suffering", "problem",
                        "recommend", "suggest", "which doctor", "what doctor", "specialist",
                        "cough", "fever", "headache", "stomach", "back", "rash", "fatigue",
                        "hurt", "hurts", "sick", "ill", "unwell"]
    if any(keyword in msg for keyword in symptom_keywords):
        doctors, reply = get_doctor_recommendations(msg, db)
        return ChatResponse(reply=reply)

    # 5. Appointment assistance
    if any(word in msg for word in ["appointment", "book", "schedule", "cancel", "reschedule"]):
        return ChatResponse(reply="I can help with appointments! You can book, cancel, or reschedule from your 'Appointments' dashboard. If you need step-by-step guidance, just ask!")

    # 6. General help
    if "help" in msg:
        return ChatResponse(reply="I can assist you with:\n- Symptom‑based guidance and doctor suggestions\n- Medication information\n- Appointment booking questions\n- Health FAQs\n- Hospital information\n- Medical records and emergency info\n\nJust type your question!")

    # 7. Fallback
    return ChatResponse(reply="I'm sorry, I didn't quite understand that. Try asking about symptoms, medications, appointments, or type 'Health FAQs', 'Medication information', 'Emergency', or 'Medical records'.")